Position Multi-QMs
VisualMQ/VisualMQ pull request #36
Opened 2021-07-14 17:00 UTC by huyifanx

This branch is based on Diallo's dynamic update branch.

2021-07-14 20:22 UTC, phillip-tian commented on Assets/Scripts/Rendering/State.cs
> +    private List<int[]> lastQMPosition = new List<int[]>();
This list seems to contain all the rendered QM's positions, so maybe it should be called QM Positions?

2021-07-14 20:22 UTC, phillip-tian commented on Assets/Scripts/Rendering/State.cs
> +            result[0]=lastQMPosition[renderedQueueManagers-1][0]+lastQMSize[0]+10;
Try not to use magic numbers (10).

2021-07-14 20:22 UTC, phillip-tian commented on Assets/Scripts/Rendering/State.cs
> +            result[2]=lastQMPosition[renderedQueueManagers-2][2]+lastQMSize[1]+10;
Magic number

2021-07-14 20:28 UTC, phillip-tian commented
@lukasotocerny The code looks ok, I've pulled this branch and tested it locally and can confirm it correctly displays two QMs. I'm leaving this PR open for you to take a look at.
@huyifanx I made minor comments should you wish to clean the code up a little. Also, have you tried connecting to 3 QMs?

2021-07-15 03:59 UTC, huyifanx commented
@phillip-tian Yes I have tried connecting to 3 QMs, It works well. And the three comments above are very reasonable, I will fix them

2021-07-15 07:01 UTC, lukasotocerny requested changes
Great that the functionality works! I have several remarks on how to improve the code so that we remove code duplication and make it cleaner. @huyifanx let's jump on a call today and have a pair coding session where we go through it together. @phillip-tian feel free to join as well. In the meanwhile please resolve merge conflicts as I merged Diallo's branch into main earlier today.

2021-07-16 07:32 UTC, huyifanx reviewed
Nice, it looks better now

2021-07-16 07:48 UTC, lukasotocerny approved these changes
LGTM now, we'll have to figure out the text because it renders on top of everything else

2021-07-16 07:50 UTC, huyifanx commented
Yes, I am working on this problem as well. It seems that we need to change the shader of the Font

2021-07-16 07:51 UTC, merged